name: CI Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libltdl-dev \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            unzip \
            zip

      - name: Install Buildozer and Dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer
          pip install git+https://github.com/kivy/python-for-android.git

      - name: Build with Buildozer
        run: |
          rm -rf .buildozer
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-apk
          path: bin/*.apk
